---
name: Build docker image

'on':
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - 'main'
      - 'build*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QDOCKER_USERNAME }}
          password: ${{ secrets.QDOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/leet4tari/gh-pilot:latest
            ghcr.io/leet4tari/gh-pilot:1.0.0
            quay.io/leet4tari/gh-pilot:latest
            quay.io/leet4tari/gh-pilot:1.0.0

            # user/app:latest
            # user/app:1.0.0
